[project]
name = "agentic-ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=9.4.0",
    "openai>=1.93.2",
    "openai-agents>=0.1.0",
    "python-dotenv>=1.1.1",
]
